const data = {
    products:[
        {
            _id:'1',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-1.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-100.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-2.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-99.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-3.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-98.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'7',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-4.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'8',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-97.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'9',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-5.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'10',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-96.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'11',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-6.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'12',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-95.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'13',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-7.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'14',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-94.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'15',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-8.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'16',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-98.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'17',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-9.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'18',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-92.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'19',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-10.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'20',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-91.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'21',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-11.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'22',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-90.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }, {
            _id:'23',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-12.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }, {
            _id:'24',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-89.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }, {
            _id:'25',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-13.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }, {
            _id:'26',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-88.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'27',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-14.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'28',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-87.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'29',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-15.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'30',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-86.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'31',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-16.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'32',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-85.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'33',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-17.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'34',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-84.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'35',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-18.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'36',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-83.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'37',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-19.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'38',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-82.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'39',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-20.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'40',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-81.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'41',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-21.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'42',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-80.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'43',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-22.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'44',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-79.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'45',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-23.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'46',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-78.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'47',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-24.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'48',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-77.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'49',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-25.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'50',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-76.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'51',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-26.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'52',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-75.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'53',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-27.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'54',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-74.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'55',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-28.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'56',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-73.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'57',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-29.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'58',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-72.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'59',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-30.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'60',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-71.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'61',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-31.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'62',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-70.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'63',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-32.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'64',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-69.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'65',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-32.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'66',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-68.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'67',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-33.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'68',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-67.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'69',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-34.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'70',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-66.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'71',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-35.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'72',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-65.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'73',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-36.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'74',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-64.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'75',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-37.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'76',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-63.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'77',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-38.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'78',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-62.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'79',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-39.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'80',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-61.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'81',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-40.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'82',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-60.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'83',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-41.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'84',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-59.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'85',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-42.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'86',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-58.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'87',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-43.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'88',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-57.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'89',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-44.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'90',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-56.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'91',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-45.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'92',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-55.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'93',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-46.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'94',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-54.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'95',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-47.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'96',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-53.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'97',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-48.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'98',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-52.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'99',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-49.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'100',
            name :'Nike Slim Shirt',
            category:'Shirts',
            images:'/images/product-51.jpg',
            price:120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        }
    ]
}
export default data; 